repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini"]
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - types-requests

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: radon-cc
        name: radon cc check
        entry: ./scripts/run_radon.sh
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: ./scripts/test.sh
        language: system
        pass_filenames: false
